### ISSUE TITLE
Singleton pattern

### ISSUE THREAD

**Issue by derek-watson** [twg/devour-jsonapi-client#5]
I'm not sure I understand the way the singleton pattern is used here. In the readme I'm encouraged to

```javascript
let jsonApi = JsonApi.getInstance()
jsonApi.setup('http://your-api-here.com')
```

which made me think I'm getting a new instance of JsonApi and configuring it with an endpoint URL (I realized later that's not the case). If we're getting and configuring instances, I think it would be most appropriate to use the `new` keyword and pass options to the constructor:

```javascript
const jsonApi = new JsonApi({baseUrl: 'http://your-api-here.com'})
```

I looked at the code to double-check and saw this, which confirmed my suspicions:

```javascript
class JsonApi {
  ...
```

but when I looked into the code for the `getInstance()` method, I realized we're forcing a singleton pattern.

1. If using a singleton pattern, I suggest using an object literal instead of getting fancy with making a class and forcing users to use a misleading `getInstance()` method
2. I'm not sure a singleton is appropriate - wouldn't you want to ever have two objects concurrently, configured against different endpoints?

**Comment by derek-watson** [comment]
@Emerson I'm happy to submit a PR for this one if you want to tell me which way to go with it

**Comment by Emerson** [comment]
I think we went with the singleton pattern _(an admittedly janky version of it)_ in the hopes that it would be easy to define models and then pull in `jsonApi` throughout the project and know that we always had the same instance.

In hindsight, I think you're absolutely correct and that if we want to have a singleton pattern, we should handle that in the host application code rather than this library. Would be happy to see this updated 👍
